### ISSUE TITLE
moment outputs deprecation warning

### ISSUE THREAD

**Issue by Guria** [lennym/moment-business-time#13]
> Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale

**Comment by milovanderlinden** [comment]
I am getting this too.

**Comment by 1ns1d3r** [comment]
me too

**Comment by lennym** [comment]
This should be resolved at version 0.6.0 thanks to contribution from @cdibened
