### ISSUE TITLE
Multiple time ranges in a day

### ISSUE THREAD

**Issue by zoell** [lennym/moment-business-time#27]
Is it possible to define multiple time ranges for days?

Like Monday from 09:00:00 to 11:00:00 and 14:00:00 to 17:00:00?

Thanks

**Comment by lennym** [comment]
Thanks for opening an issue @zoell 

This isn't currently possible, but I can see how it would be useful. I'd be happy to accept a PR if you wanted to look at implementing it.

**Comment by dmastag** [comment]
@lennym any pointers on how to implement it?
I would happy to try to submit a PR but would appreciate some pointers

**Comment by tds100** [comment]
Quote

**Comment by chromey** [comment]
I decided to give it a go as this is the one missing feature that kept me from using this otherwise great little lib. Had to change a bit more than I anticipated, but I was (hopefully) careful not to break anything and also added a few new tests. What do you think?

**Comment by chromey** [comment]
Oh and this also fixes #24
