### ISSUE TITLE
When adding 48 hours to incorrect result

### ISSUE THREAD

**Issue by FatalErrorXDevs** [lennym/moment-business-time#33]
when i add 48 hours to Thu Sep 06 2018 12:55:49 GMT+0200 (Central European Summer Time),

i get Fri Sep 14 2018 12:55:49 GMT+0200 (Central European Summer Time) as result.

 i expect Mon Sep 10 2018 12:55:49 GMT+0200 (Central European Summer Time)

**Comment by brad-gray** [comment]
If you have are using the default `workinghours` library config it limits working hours to 9a-5p Mon-Fri (8 hours per day). 48 hours at 8 hrs/day is 6 days. Those 6 days overlap the weekend, which adds 2 more days. Fri Sep 14 is the correct date
